#!/usr/bin/env bash

# Find all zombie processes and store their process IDs in an array
zombies=$(ps -A -o stat,pid | grep -w Z | awk '{print $2}')

# Iterate through the list of zombie PIDs
for pid in $zombies; do
    # Kill the zombie process
    kill -9 $pid
done
