#!/usr/bin/env bash

# Find all zombie processes
zombie_processes=$(ps -eo state | grep -w Z)

# Iterate over the zombie processes and kill them
for zombie in $zombie_processes; do
  pid=$(echo $zombie | awk '{print $1}')
  kill -9 $pid
done
